version: 1
external_links:
  documentation: "https://nslogmeng.github.io/swift-service/documentation/service/?utm_source=swiftpackageindex&utm_medium=referral&utm_campaign=service-spi&utm_content=package-docs"