name: Deploy DocC to GitHub Pages
description: Download language artifacts, combine, inject Google Analytics, upload Pages artifact, and deploy.

inputs:
  default_lang:
    required: true
    description: Default language identifier, e.g. en.
  langs_json:
    required: true
    description: JSON array string of all supported languages, e.g. ["en","zh-Hans"].
  ga_measurement_id:
    required: false
    description: GA4 Measurement ID. If empty, injection is skipped.

outputs:
  page_url:
    description: Deployed Pages URL
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: composite
  steps:
    - name: Download docs artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: docs-*
        merge-multiple: false

    - name: Combine Documentation
      shell: bash
      run: |
        set -euo pipefail

        rm -rf .build/docs
        mkdir -p .build/docs

        LANG_LIST=$(echo '${{ inputs.langs_json }}' | tr -d '[]"' | tr ',' ' ')
        for lang in $LANG_LIST; do
          lang_dir="docs-$lang"
          tarball="$lang_dir/docs-$lang.tar.gz"

          if [ -f "$tarball" ]; then
            if [ "$lang" = "${{ inputs.default_lang }}" ]; then
              tar -xzf "$tarball" -C .build/docs
            else
              mkdir -p ".build/docs/$lang"
              tar -xzf "$tarball" -C ".build/docs/$lang"
            fi
          fi
        done

        # Disable Jekyll processing on GitHub Pages.
        touch .build/docs/.nojekyll

    - name: Inject Google Analytics
      uses: ./.github/actions/inject-google-analytics
      with:
        root: .build/docs
        measurement_id: ${{ inputs.ga_measurement_id }}

    - name: Inject root index.html with language redirect
      uses: ./.github/actions/inject-root-redirect
      with:
        root: .build/docs
        default_lang: ${{ inputs.default_lang }}
        langs_json: ${{ inputs.langs_json }}

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .build/docs

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
