name: Inject Root Redirect Page
description: Add redirect logic to index.html files without breaking SPA functionality.

inputs:
  root:
    required: true
    description: Root directory containing the DocC static site.
  default_lang:
    required: true
    description: Default language identifier, e.g. en.
  langs_json:
    required: true
    description: JSON array string of all supported languages, e.g. ["en","zh-Hans"].

runs:
  using: composite
  steps:
    - name: Add redirect logic to index.html files
      shell: bash
      env:
        ROOT: ${{ inputs.root }}
        DEFAULT_LANG: ${{ inputs.default_lang }}
        LANGS_JSON: ${{ inputs.langs_json }}
      run: |
        set -euo pipefail

        LANG_LIST=$(echo "$LANGS_JSON" | tr -d '[]"' | tr ',' ' ')

        # Function to inject redirect script into index.html
        inject_redirect() {
          local file="$1"
          local redirect_path="$2"
          local lang_code="${3:-}"
          
          if [ ! -f "$file" ]; then
            echo "Warning: File not found: $file"
            return
          fi

          # Extract baseUrl from existing script tag
          local base_url=""
          if grep -q 'var baseUrl =' "$file"; then
            base_url=$(grep -o 'var baseUrl = "[^"]*"' "$file" | sed 's/var baseUrl = "\([^"]*\)"/\1/')
          fi

          # Build redirect script
          local redirect_script
          if [ -z "$lang_code" ]; then
            # Root redirect: / -> /documentation/service/
            redirect_script="    <script>
              // Redirect root path to documentation
              (function() {
                const pathname = window.location.pathname;
                const baseUrl = \"${base_url}\";
                let normalizedPath = pathname.endsWith('/') ? pathname.slice(0, -1) : pathname;
                normalizedPath = normalizedPath || '/';
                let normalizedBase = baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl;
                normalizedBase = normalizedBase || '';
                if (normalizedPath === normalizedBase || (normalizedBase === '' && normalizedPath === '/')) {
                  // Ensure no double slashes when concatenating
                  const redirectPath = \"${redirect_path}\";
                  const finalPath = (baseUrl.endsWith('/') && redirectPath.startsWith('/')) 
                    ? baseUrl + redirectPath.slice(1) 
                    : baseUrl + redirectPath;
                  window.location.href = finalPath;
                }
              })();
            </script>"
          else
            # Language redirect: /zh-Hans/ -> /zh-Hans/documentation/service/
            redirect_script="    <script>
              // Redirect language root path to documentation
              (function() {
                const pathname = window.location.pathname;
                const baseUrl = \"${base_url}\";
                let normalizedPath = pathname.endsWith('/') ? pathname.slice(0, -1) : pathname;
                normalizedPath = normalizedPath || '/';
                let normalizedBase = baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl;
                normalizedBase = normalizedBase || '';
                // For language-specific pages, baseUrl already includes the language path
                // So we check if the current path matches the baseUrl (language root)
                if (normalizedPath === normalizedBase) {
                  let redirectPath = \"${redirect_path}\";
                  // If redirectPath starts with /${lang_code}/, remove the language prefix
                  // since baseUrl already includes the language path
                  const langPrefix = \"/${lang_code}/\";
                  if (redirectPath.startsWith(langPrefix)) {
                    redirectPath = redirectPath.slice(langPrefix.length - 1); // Remove /zh-Hans, keep the leading /
                  }
                  // Ensure no double slashes when concatenating
                  const finalPath = (baseUrl.endsWith('/') && redirectPath.startsWith('/')) 
                    ? baseUrl + redirectPath.slice(1) 
                    : baseUrl + redirectPath;
                  console.log('normalizedPath', normalizedPath);
                  console.log('normalizedBase', normalizedBase);
                  console.log('redirectPath', redirectPath);
                  console.log('baseUrl', baseUrl);
                  console.log('finalPath', finalPath);
                  window.location.href = finalPath;
                }
              })();
            </script>"
          fi

          # Check if redirect script already exists
          if grep -q "Redirect.*path to documentation" "$file"; then
            echo "Redirect script already exists in $file, skipping"
            return
          fi

          # Insert redirect script after <head> tag
          # Create a temporary file with the script
          local script_file=$(mktemp)
          echo "$redirect_script" > "$script_file"
          
          # Use sed to insert script after <head> tag (case insensitive)
          local temp_file=$(mktemp)
          sed -E '/<[Hh][Ee][Aa][Dd][^>]*>/r '"$script_file" "$file" > "$temp_file"
          
          # Replace original file and cleanup
          mv "$temp_file" "$file"
          rm -f "$script_file"
          
          echo "Added redirect logic to $file"
        }

        # Add redirect logic to root index.html
        ROOT_INDEX="$ROOT/index.html"
        if [ -f "$ROOT_INDEX" ]; then
          inject_redirect "$ROOT_INDEX" "/documentation/service/" ""
        fi

        # Add redirect logic to language-specific index.html files
        for lang in $LANG_LIST; do
          if [ "$lang" != "$DEFAULT_LANG" ]; then
            lang_path="/$lang/documentation/service/"
            lang_index="$ROOT/$lang/index.html"
            if [ -f "$lang_index" ]; then
              inject_redirect "$lang_index" "$lang_path" "$lang"
            fi
          fi
        done

        echo "Added redirect logic to index.html files without breaking SPA"
